services:
  sass-rabbitmq:
    image: rabbitmq:3-management
    container_name: sass-rabbitmq
    ports:
      - "5673:5672"  # Changed left port to avoid conflict with old project
      - "15673:15672" # Changed left port to avoid conflict with old project
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}


  sass-node-express:
    build: .
    depends_on:
      - sass-rabbitmq
    env_file:
      - .env
    ports:
      - "4002:4000" # Changed left port to avoid conflict with old project
    volumes:
      - .:/app
    command: npm run dev


